In [1]:
import pandas as pd
import requests
import numpy as np
from bs4 import BeautifulSoup

In [2]:
#r = requests.get('https://www.google.com/search?source=hp&ei=71VQXPOJKYq9jwSPmr2AAg&q=google+stocks&btnK=Google+Search&oq=google+stocks&gs_l=psy-ab.3..0l10.5209.9745..10027...3.0..0.380.4905.2-6j10......0....1..gws-wiz.....0..35i39j0i131j0i10.X0G6cPLukyE')
r = requests.get('https://www.edureka.co/big-data-and-analytics')#('https://www.edureka.co/cloud-computing-certification-courses')

In [3]:
r # 200 is succesfull and anything other and 200 it is failure

<Response [200]>

In [4]:
c = r.content
c
#soup =BeautifulSoup(c,"html.parser")

b'\n<!DOCTYPE html>\n<html lang="en">\n    <head>\n        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\n        <!-- WARNING: Respond.js doesn\'t work if you view the page via file:// -->\n        <!--[if lt IE 9]>\n              <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>\n              <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>\n            <![endif]-->\n                    <script>var isSearchKeywordsDisplayAllowed = false;</script>\n                <script type="text/javascript">\n    // load script after pageload : TODO\n\n            (function(w,d,t,r,u){var f,n,i;w[u]=w[u]||[],f=function(){var o={ti:"4065243"};o.q=w[u],w[u]=new UET(o),w[u].push("pageLoad")},n=d.createElement(t),n.src=r,n.async=1,n.onload=n.onreadystatechange=function(){var s=this.readyState;s&&s!=="loaded"&&s!=="complete"||(f(),n.onload=n.onreadystatechange=null)},i=d.getElementsByTagName(t)[0],i.paren

In [6]:
soup =BeautifulSoup(c,"html.parser")
soup


<!DOCTYPE html>

<html lang="en">
<head>
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
              <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
              <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
            <![endif]-->
<script>var isSearchKeywordsDisplayAllowed = false;</script>
<script type="text/javascript">
    // load script after pageload : TODO

            (function(w,d,t,r,u){var f,n,i;w[u]=w[u]||[],f=function(){var o={ti:"4065243"};o.q=w[u],w[u]=new UET(o),w[u].push("pageLoad")},n=d.createElement(t),n.src=r,n.async=1,n.onload=n.onreadystatechange=function(){var s=this.readyState;s&&s!=="loaded"&&s!=="complete"||(f(),n.onload=n.onreadystatechange=null)},i=d.getElementsByTagName(t)[0],i.parentNode.insertBefore(n,i)})(window,document,"script","//bat.bing.com/bat.js","uetq

In [10]:
course = soup.findAll("div",{"class":"clp-course-tile"})
course

[<div class="clp-course-tile">
 <div class="clp-course-img-div">
 <img alt="course-img" class="clp-course-img img-responsive hidden-xs" src="https://d1jnx9ba8s6j9r.cloudfront.net/imgver.1550154563/img/co_img_523_1540474151.svg"/><img alt="course-img" class="clp-course-img hidden-lg hidden-md hidden-sm" src="https://d1jnx9ba8s6j9r.cloudfront.net/imgver.1550154563/img/s/co_img_523_1540474151.svg"/><img alt="ms-best-seller" class="best-seller" src="https://d1jnx9ba8s6j9r.cloudfront.net/imgver.1550154563/img/best-seller-min.svg"/> </div>
 <div class="clp-course-details">
 <h3 class="title">Big Data Hadoop Certification Training </h3>
 <ul class="highlights">
 <li>
 <i class="icon-total-learners"></i>
 <span>143k Enrolled Learners</span>
 </li>
 <li>
 <i class="icon-calender"></i>
 <span>Weekend/Weekday</span>
 </li>
 <li class="hidden-xs">
 <i class="icon-live-instructor"></i>
 <span>Live Class</span>
 </li>
 </ul>
 <span class="reviewstitle hidden-xs">Reviews</span>
 <div class="reviews-s

In [11]:
a = course[0]
a

<div class="clp-course-tile">
<div class="clp-course-img-div">
<img alt="course-img" class="clp-course-img img-responsive hidden-xs" src="https://d1jnx9ba8s6j9r.cloudfront.net/imgver.1550154563/img/co_img_523_1540474151.svg"/><img alt="course-img" class="clp-course-img hidden-lg hidden-md hidden-sm" src="https://d1jnx9ba8s6j9r.cloudfront.net/imgver.1550154563/img/s/co_img_523_1540474151.svg"/><img alt="ms-best-seller" class="best-seller" src="https://d1jnx9ba8s6j9r.cloudfront.net/imgver.1550154563/img/best-seller-min.svg"/> </div>
<div class="clp-course-details">
<h3 class="title">Big Data Hadoop Certification Training </h3>
<ul class="highlights">
<li>
<i class="icon-total-learners"></i>
<span>143k Enrolled Learners</span>
</li>
<li>
<i class="icon-calender"></i>
<span>Weekend/Weekday</span>
</li>
<li class="hidden-xs">
<i class="icon-live-instructor"></i>
<span>Live Class</span>
</li>
</ul>
<span class="reviewstitle hidden-xs">Reviews</span>
<div class="reviews-stars">
<i aria-hidden

In [38]:
a.find("h3",{"class":"title"}).text.strip()

'Big Data Hadoop Certification Training'

In [43]:
a.find("span",{"class":"reviewstitle hidden-xs"}).text.strip()

'Reviews'

In [44]:
a.find("div",{"class":"reviews-stars"}).text.strip()

'5 (57150)'

In [45]:
import pandas as pd

In [46]:
df = pd.DataFrame(columns=['Name','Price','Offer'])

In [47]:
df

Empty DataFrame
Columns: [Name, Price, Offer]
Index: []

In [48]:
for z in course:
    Name1= z.find("h3",{"class":"title"}).text.strip()
    Price1= z.find("span",{"class":"reviewstitle hidden-xs"}).text.strip()
    Offer1= z.find("div",{"class":"reviews-stars"}).text.strip()
    df1 = pd.DataFrame([[Name1,Price1,Offer1]],columns = ['Name','Price','Offer'])
    df = df.append(df1)

In [49]:
df

Name    Price      Offer
0       Big Data Hadoop Certification Training  Reviews  5 (57150)
0  Apache Spark and Scala Certification Tra...  Reviews   5 (9250)
0          Apache Kafka Certification Training  Reviews   5 (1900)
0  Python Spark Certification Training usin...  Reviews    5 (800)
0      Splunk Training & Certification- Pow...  Reviews   5 (2250)
0  Hadoop Administration Certification Trai...  Reviews   5 (9550)
0           ELK Stack Training & Certification  Reviews    5 (250)
0  Comprehensive HBase Certification Traini...  Reviews    5 (400)
0           Apache Solr Certification Training  Reviews   5 (2450)
0     Comprehensive Pig Certification Training  Reviews    4 (450)
0  MapReduce Design Patterns Certification ...  Reviews    5 (400)
0  Comprehensive Hive Certification Trainin...  Reviews    5 (650)
0          Apache Storm Certification Training  Reviews   5 (2200)
0  Mastering Apache Ambari Certification Tr...  Reviews    5 (500)
0  Comprehensive MapReduce Certification Tr...  Reviews    5 (650)

In [17]:
df.reset_index()
#df.to_excel('ERaghu.xlsx',index=False)

index                                         Name    Price      Offer
0       0       Big Data Hadoop Certification Training  Reviews  5 (57150)
1       0  Apache Spark and Scala Certification Tra...  Reviews   5 (9250)
2       0          Apache Kafka Certification Training  Reviews   5 (1900)
3       0  Python Spark Certification Training usin...  Reviews    5 (800)
4       0      Splunk Training & Certification- Pow...  Reviews   5 (2250)
5       0  Hadoop Administration Certification Trai...  Reviews   5 (9550)
6       0           ELK Stack Training & Certification  Reviews    5 (250)
7       0  Comprehensive HBase Certification Traini...  Reviews    5 (400)
8       0           Apache Solr Certification Training  Reviews   5 (2450)
9       0     Comprehensive Pig Certification Training  Reviews    4 (450)
10      0  MapReduce Design Patterns Certification ...  Reviews    5 (400)
11      0  Comprehensive Hive Certification Trainin...  Reviews    5 (650)
12      0          Apache Storm Certification Training  Reviews   5 (2200)
13      0  Mastering Apache Ambari Certification Tr...  Reviews    5 (500)
14      0  Comprehensive MapReduce Certification Tr...  Reviews    5 (650)

In [18]:
df.dtypes

Name     object
Price    object
Offer    object
dtype: object

In [19]:
#df['Price']=df['Price'].str.replace(',','').astype(np.int64)
#df['Offer']=df['Offer'].str.replace(',','').astype(np.int64)

In [20]:
df.dtypes

Name     object
Price    object
Offer    object
dtype: object

In [21]:
!pip install bkcharts

In [22]:
from bokeh.plotting import output_file,show,figure
from bokeh.io import output_notebook

In [23]:
dataset = pd.DataFrame(columns = ['X','Y'])
dataset['X'] = [1,2,3,4,5]
dataset['Y'] = [1,4,9,16,25]
dataset

X   Y
0  1   1
1  2   4
2  3   9
3  4  16
4  5  25

In [24]:
p = figure(plot_width = 500,plot_height = 400)
p.square_cross(dataset['X'],dataset['Y'],size =5)
output_file('Scatter_charts.html')
show(p)

In [25]:
dataset1 = pd.read_excel('verlegenhuken.xlsx')

In [26]:
dataset1.head()

Year  Month  Day  Hour  Temperature  Pressure
0  2010     10    6     3          -30      9984
1  2010     10    6     9          -28      9992
2  2010     10    6    10          -24      9987
3  2010     10    6    11          -19      9987
4  2010     10    6    12          -19      9985

In [27]:
dataset1['Temperature']= dataset1['Temperature']/10
dataset1['Pressure']= dataset1['Pressure']/10

In [28]:
dataset1.head()

Year  Month  Day  Hour  Temperature  Pressure
0  2010     10    6     3         -3.0     998.4
1  2010     10    6     9         -2.8     999.2
2  2010     10    6    10         -2.4     998.7
3  2010     10    6    11         -1.9     998.7
4  2010     10    6    12         -1.9     998.5

In [29]:
p = figure(plot_width = 1000,plot_height = 1000)
p.circle(dataset1['Temperature'],dataset1['Pressure'],size =5)
output_file('Weather.html')
show(p)

# Open CV Image Reading

In [30]:
import cv2
print(cv2.__version__)

4.0.1


In [31]:
img = cv2.imread('Penguins.jpg',1)#im = image read and 1 = color image or 0 = black and white image

In [32]:
img

array([[[153, 134, 119],
        [152, 133, 118],
        [150, 131, 116],
        ...,
        [120, 101,  96],
        [120, 101,  96],
        [119, 100,  95]],

       [[152, 133, 118],
        [151, 132, 117],
        [150, 131, 116],
        ...,
        [120, 101,  96],
        [120, 101,  96],
        [121, 102,  97]],

       [[151, 132, 117],
        [151, 132, 117],
        [149, 130, 115],
        ...,
        [120, 101,  96],
        [121, 102,  97],
        [122, 103,  98]],

       ...,

       [[252, 234, 223],
        [252, 235, 222],
        [251, 234, 221],
        ...,
        [233, 215, 204],
        [233, 215, 204],
        [234, 216, 205]],

       [[249, 232, 219],
        [249, 233, 217],
        [249, 233, 217],
        ...,
        [233, 216, 203],
        [233, 216, 203],
        [233, 216, 203]],

       [[249, 233, 217],
        [249, 233, 217],
        [249, 233, 217],
        ...,
        [233, 216, 203],
        [233, 216, 203],
        [233, 216, 203]]

In [33]:
img_1 = cv2.imread('Penguins.jpg',0)#im = image read and 1 = color image or 0 = black and white image

In [34]:
img_1

array([[132, 131, 129, ..., 102, 102, 101],
       [131, 130, 129, ..., 102, 102, 103],
       [130, 130, 128, ..., 102, 103, 104],
       ...,
       [233, 233, 232, ..., 214, 214, 215],
       [230, 230, 230, ..., 214, 214, 214],
       [230, 230, 230, ..., 214, 214, 214]], dtype=uint8)

In [35]:
# cv2.imshow("3 Penguins",img)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [36]:
img.shape

(1266, 1900, 3)

In [37]:
cv2.imshow('Penguins',img)
cv2.waitKey(0)

-1

In [38]:
cv2.imshow('Penguins',img_1)
cv2.waitKey(0)

-1

In [39]:
img.size

7216200

In [40]:
img.shape[1]/2

950.0

In [41]:
# Image Resize

imgsiz = cv2.imread('Penguins.jpg',0)
resized_image=cv2.resize(img,(int(img.shape[1]/2),int(img.shape[0]/2)))
cv2.imshow('Penguins',resized_image)
cv2.imwrite('Penguins_resized.png',resized_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Face Dectection for Image

In [42]:
#print(face_cascade.empty()) # To check face_cascade is empty or not check this link https://stackoverflow.com/questions/30508922/error-215-empty-in-function-detectmultiscale
#print(r'D:\folder Name\haarcascade_frontalface_default.xml')# get the path

In [43]:
#Create a CascadeClassifier Object
face_cascade=cv2.CascadeClassifier("C://Users//G705961//Desktop//Python//t1ub3ntt6c//539_m8_codes_v1.0//539_m8_codes_v1.0//haarcascade_frontalface_default.xml")

In [44]:
#r = cv2.imread('Raghavendra Rao Kotlur.jpg',1)#im = image read and 1 = color image or 0 = black and white image
r = cv2.imread('Actor.jpg',1)
gray_img = cv2.cvtColor(r,cv2.COLOR_BGR2GRAY)#Reading the image as gray scale image

In [45]:
faces1 = face_cascade.detectMultiScale(gray_img,minNeighbors=5)

In [46]:
type(faces1)

numpy.ndarray

In [47]:
faces1

array([[384,  21,  60,  60],
       [319, 210,  63,  63],
       [499, 177,  57,  57],
       [272,  38,  59,  59],
       [194, 196,  60,  60]], dtype=int32)

In [48]:
for x,y,z,h in faces1:
    r1 = cv2.rectangle(r,(x,y),(x+z,y+h),(0,0,255),3)

In [49]:
cv2.imshow("Raghavendra Rao Kotlur",r1)
cv2.imwrite("Raghavendra.png",r1)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Face Dectection for Video

In [50]:
import cv2,time

In [51]:
video=cv2.VideoCapture(0)
check,frame = video.read()
print(check)
print(frame)
time.sleep(5)
cv2.imshow('Capturing',frame)
cv2.waitKey(0)
video.release()
cv2.destroyAllWindows

True
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


<function destroyAllWindows>

In [52]:
#Loop video for face dectection

In [53]:
video=cv2.VideoCapture(0)
a = 1
while True:
    check,frame = video.read()
    print(frame)
    gray_video = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)#Reading the image as gray scale video
    cv2.imshow('Capturing',gray_video)
    key = cv2.waitKey(1)
    if key == ord('s'):
        break
print(a)# This will print the numbers of frames
video.release()
cv2.destroyAllWindows()

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...


[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...


[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...


[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...


[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...


[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...


[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...


[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...


[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...


[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...


[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...


[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...


[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...


[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...


[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...


# Motion Detector

In [83]:
first_frame = None
video=cv2.VideoCapture(0)#create a video capture object to record video using webcam
while True:
    check,frame=video.read()
    gray=cv2.cvtColor(fram,cv2.COLOR_BGR2GRAY)#convert the frame color to gray scale
    gray=cv2.GaussianBlur(gray,(21,21),0)#convert the gray scale frame to Gaussian Blur
    if first_frame==None:# this is used to store the first image/frame of video
        first_frame=gray
        continue
delta_frame=cv2.absdiff(first_frame,gray)#calculates the difference between first frame and other frames
thresh_delta=cv2.threshold(delta_frame,30,255,cv2.THRESH_BINARY)[1]#Provides a threshold value,such that if will conver the difference value with less than 30 to black.if the difference is greater than 30 it will convert those pixels to white
thresh_delta=cv2.dilate(thresh_delta,None,iterations=0#Provides a threshold value,such that if will conver the difference value with less than 30 to black.if the difference is greater than 30 it will convert those pixels to white
(_,cnts,_) = cv2.findContours(thresh_delta.copy(),cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)

for contour in cnts:
    if cv2.contourArea(contour)<1000:
        continue
#Above code remove noises and shadows.Bascially, it will keep only that part white, which has area greater than 1000 pixels        
    (x,y,w,h)=cv2.boundingRect(contour)
#Creates a rectangular box around the object in the frame
    cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255),3)
cv2.imshow('frame',frame)
cv2.imshow('Capturing',gray)
cv2.imshow('delta',delta_frame)
cv2.imshow('thresh',thresh_delta)
key1=cv2.waitKey(1)
if(key==ord('q')):
    break
video.release()
cv2.destroyAllWindows

SyntaxError: invalid syntax (<ipython-input-83-12d570806b7b>, line 13)

In [85]:
first_frame = None
status_list=[None,None]
times=[]
df=pd.DataFrame(columns=["Start","End"])
video=cv2.VideoCapture(0)
while True:
    check,frame = video.read()
    status=0
    gray= cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    gray = cv2.GaussianBlur(gray,(21,21),0)
(,cnts,)=cv2.findContours(thresh_frame.copy(),cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
for contour in cnts:
    if cv2.contourArea(contour)<10000:
        continue
    status=1
(x,y,w,h)=cv2.boundingRectu(contour)
cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,0),3)
if status[-1]==1and status_list[-2]==0:
    times.append(datetime.now())
if status[-1]==1and status_list[-2]==1:
    times.append(datetime.now())

SyntaxError: invalid syntax (<ipython-input-85-3d083139cfd0>, line 11)